const CHUNK_PUBLIC_PATH = "server/pages/baby/[babyId].js";
const runtime = require("../../chunks/ssr/[turbopack]_runtime.js");
runtime.loadChunk("server/chunks/ssr/node_modules_bf671b14._.js");
runtime.loadChunk("server/chunks/ssr/[root-of-the-server]__a1cbfe23._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_3d826c06._.js");
runtime.loadChunk("server/chunks/ssr/[root-of-the-server]__a0916276._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_date-fns_60e25135._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_@floating-ui_react_dist_0a29d835._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_react-datepicker_dist_index_es_b18b64f0.js");
runtime.loadChunk("server/chunks/ssr/node_modules_c4227d1b._.js");
runtime.loadChunk("server/chunks/ssr/pages_baby_[babyId]_tsx_3c7d031e._.js");
runtime.getOrInstantiateRuntimeModule("[project]/node_modules/next/dist/esm/build/templates/pages.js { INNER_PAGE => \"[project]/pages/baby/[babyId].tsx [ssr] (ecmascript)\", INNER_DOCUMENT => \"[project]/pages/_document.tsx [ssr] (ecmascript)\", INNER_APP => \"[project]/pages/_app.tsx [ssr] (ecmascript)\" } [ssr] (ecmascript)", CHUNK_PUBLIC_PATH);
module.exports = runtime.getOrInstantiateRuntimeModule("[project]/node_modules/next/dist/esm/build/templates/pages.js { INNER_PAGE => \"[project]/pages/baby/[babyId].tsx [ssr] (ecmascript)\", INNER_DOCUMENT => \"[project]/pages/_document.tsx [ssr] (ecmascript)\", INNER_APP => \"[project]/pages/_app.tsx [ssr] (ecmascript)\" } [ssr] (ecmascript)", CHUNK_PUBLIC_PATH).exports;
